### ISSUE TITLE
JS-framework: field props

### ISSUE THREAD

**Issue by jusper-dk** [Plumsail/forms-docs#16]
`fd.field('DropDown0').required = false`
For SharePoint fields, it only hides/shows asterisk, the validation remains.
For Plumsail Fields, it also adds validation.

`fd.field('DropDown').clear()`
Clears the field

`fd.field('TextBox0').placeholder`
Gets or sets placeholder where applicable

`fd.field('DropDown0').widget `
Returns jquery-object lying under the Vue-component. Usually its kendo-widget.

`fd.field('DropDown0').value`
You must describe type of the value for each form field and provide samples.

```
fd.field('DropDown0').$on('change', function(value) {
    alert('New value: ' + value);
})
```

**Comment by Vrolok15** [comment]
Done
