### ISSUE TITLE
Menu item must become orange when it's hovered

### ISSUE THREAD

**Issue by jusper-dk** [Plumsail/forms-docs#20]
![image](https://user-images.githubusercontent.com/27721442/32775638-0cbec17a-c941-11e7-90d3-8739197cf86b.png)

the same here:
![image](https://user-images.githubusercontent.com/27721442/32775770-753551ba-c941-11e7-95a4-023456c4c5a2.png)

**Comment by Vrolok15** [comment]
Solved
